
services:
  # Backend service
  foosballdtu-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
    - SUPABASE_URL=${SUPABASE_URL}
    - SUPABASE_KEY=${SUPABASE_KEY}
    - GIN_MODE=release
    networks:
    - foosball-network
    restart: unless-stopped

  # Frontend service
  foosballdtu-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
        BACKEND_URL: ${BACKEND_URL}
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/foosball-dtu/}
    container_name: frontend
    ports:
    - "80:80"
    networks:
    - foosball-network
    restart: unless-stopped

networks:
  foosball-network:
    driver: bridge

