
services:
  # Backend service
  foosballdtu-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
    - SUPABASE_URL=${SUPABASE_URL}
    - SUPABASE_KEY=${SUPABASE_KEY}
    - GIN_MODE=release
    networks:
    - foosball-network
    restart: unless-stopped

  # Frontend service
  foosballdtu-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: ${SUPABASE_URL}
        VITE_SUPABASE_PUBLISHABLE_KEY: ${SUPABASE_PUBLISHABLE_KEY}
    container_name: frontend
    ports:
    - "80:80"
    environment:
    - BACKEND_URL=${BACKEND_URL}
    networks:
    - foosball-network
    restart: unless-stopped

networks:
  foosball-network:
    driver: bridge

